apiVersion: v1
entries:
  vcs:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-07T09:14:55.4302058Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 995d367d145b4cb29105d0bc83746451640b6252d0aaffc2d0e784187b800580
    home: vcs.zaakonline.nl
    icon: vcs.zaakonline.nl
    name: vcs
    urls:
    - vcs-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-07T09:14:55.423646Z"
